[package]
name = "emnes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
sdl2 = "0.34.0"
rand = "=0.7.3"
